apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:  # Selector añadido
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:  # Labels que matchean con el selector
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root1234"
            - name: MYSQL_DATABASE
              value: "projects_db"
            - name: MYSQL_USER
              value: "bilbo"
            - name: MYSQL_PASSWORD
              value: "bilbobolson117"
            - name: MYSQL_EXTRA_DATABASES
              value: "files_db"
            - name: MYSQL_EXTRA_INIT_SCRIPT
              value: |
                ALTER USER 'bilbo'@'%' IDENTIFIED WITH mysql_native_password BY 'bilbobolson117';
                GRANT ALL PRIVILEGES ON files_db.* TO 'bilbo'@'%';
                FLUSH PRIVILEGES;
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:  # sección volumes añadida
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc  # Asegúrate de crear este PVC