apiVersion: v1
kind: ConfigMap
metadata:
  name: project-config
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/projects_db?allowPublicKeyRetrieval=true&useSSL=false"
  SPRING_DATASOURCE_USERNAME: "bilbo"
  SPRING_DATASOURCE_PASSWORD: "bilbobolson117"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SERVER_PORT: "8082"
