apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: project-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: project-deployment
  minReplicas: 1  # Mínimo de pods
  maxReplicas: 3  # Máximo de pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40  # Escala si el uso supera el 40%
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 40  # Escala si el uso supera el 40%