apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
    spec:
      containers:
        - name: file-service
          image: ragnarlodbrokv/file-service:latest
          imagePullPolicy: Always
          env:
            - name: MANAGEMENT_ENDPOINT_HEALTH_ENABLED
              value: "true"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,info"
            - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
              value: "always"
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: file-config
          volumeMounts:
            - name: uploads-volume
              mountPath: /app/uploads
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
      volumes:
        - name: uploads-volume
          persistentVolumeClaim:
            claimName: file-uploads-pvc